site_name: Ben's Code Journal
nav:
  - Algorithms:
      - Python:
          - Folder\File Compare: notes/algorithms/python/directory_compare.md
          - CSV Loader: notes/algorithms/python/csv_loader.md
          - Wheel: notes/algorithms/python/wheel/wheel.md
          - Breadth First Search: notes/algorithms/python/breadth_first_search.md
          - Names and Dates: notes/algorithms/python/names_and_dates.md
          - Alphabet Rangoli: notes/algorithms/python/alphabet_rangoli.md
          - Averages: notes/algorithms/python/averages.md
          - Collections Counter: notes/algorithms/python/collections_counter.md
          - Default Dict: notes/algorithms/python/default_dict.md
          - Door Mat: notes/algorithms/python/door_mat.md
          - Find a String: notes/algorithms/python/find_a_string.md
          - sWAP cASE: notes/algorithms/python/swap_case.md
          - Class Quiz: notes/algorithms/python/class_quiz.md
          - Print Directory: notes/algorithms/python/print_directory.md
          - Node w Classes: notes/algorithms/python/nodes_w_classes.md
          - Crossing Rects: notes/algorithms/python/crossing_rects.md
          - Retry: notes/algorithms/python/retry.md
          - Stairs: notes/algorithms/python/stairs.md
          - Insertion Sort: notes/algorithms/python/insertion_sort.md
          - Merge Sort: notes/algorithms/python/merge_sort.md
          - Tim Sort: notes/algorithms/python/tim_sort.md
          - Quick Sort: notes/algorithms/python/quick_sort.md
          - Binary Search: notes/algorithms/python/binary_search.md
  - Codalab:
      - Docker Submission: notes/codalab/docker_submission.md
  - CouchDB:
      - As container: notes/couchdb/container.md
      - Basics: notes/couchdb/basics.md
  - Data Science:
      - Coursera:
          - Machine Learning:
              - 1. Intro and Regression: notes/data_science/Coursera/machine_learning/Intro_and_Regression.md
              - 2. Classification: notes/data_science/Coursera/machine_learning/Classification_IBM.md
              - 3. Decision Trees: notes/data_science/Coursera/machine_learning/Decision_Trees_IBM.md
              - 4. Regression Trees: notes/data_science/Coursera/machine_learning/Regression_Trees_IBM.md
              - 5. Logistic Regression: notes/data_science/Coursera/machine_learning/Logistic_Regression_IBM.md
              - 6. Support Vector Machine: notes/data_science/Coursera/machine_learning/Support_Vector_Machine.md
              - 7. Multiclass Prediction: notes/data_science/Coursera/machine_learning/Multiclass_Prediction.md
              - 8. Clustering: notes/data_science/Coursera/machine_learning/Clustering.md
          - Keras:
              - 1. Intro to Neural Networks and Deep Learning: notes/data_science/Coursera/keras/Intro_Deep_Neural_Nets.md
              - 2. Artificial Neural Networks: notes/data_science/Coursera/keras/Artificial_Neural_Networks.md
              - 3. Keras and Deep Learning Libraries: notes/data_science/Coursera/keras/Keras_And_Deep_Learning_Libraries.md
              - 4. Deep Learning Models: notes/data_science/Coursera/keras/Deep_Learning_Models.md
          - Computer Vision:
              - 1. Overview: notes/data_science/Coursera/computer_vision/Overview.md
              - 2. What Is A Digital Image: notes/data_science/Coursera/computer_vision/What_Is_A_Digital_Image.md
              - 3. Image Processing With Pillow: notes/data_science/Coursera/computer_vision/Image_Processing_With_Pillow.md
              - 4. Manipulating Images: notes/data_science/Coursera/computer_vision/Manipulating_Images.md
              - 5. Pixel Transformations: notes/data_science/Coursera/computer_vision/Pixel_Transformations.md
              - 6. Geometric Operations: notes/data_science/Coursera/computer_vision/Geometric_Operations.md
              - 7. Spatial Operations In Image Processing: notes/data_science/Coursera/computer_vision/Spatial_Operations_In_Image_Processing.md
              - 8. Image Classification: notes/data_science/Coursera/computer_vision/Image_Classification.md
  - Docker:
      - Install: notes/docker/install.md
      - Basics: notes/docker/basics.md
      - Tutorial: notes/docker/tutorial.md
      - Remote Registry: notes/docker/remote_registry.md
      - Docker Compose: notes/docker/docker-compose.md
      - Impersonate: notes/docker/impersonate.md
  - Fast.ai:
      - Introduction: notes/fast.ai/introduction.md
      - Lessons (Part 1): notes/fast.ai/lessons_part_1.md
  - Git:
      - Basics: notes/git/git_basics.md
      - Git Tricks w Rob: notes/git/git_tricks_with_rob.md
      - Subtrees: notes/git/git_sub_trees.md
      - Submodules: notes/git/git_submodules.md
  - GPU Notes:
      - MIG: notes/gpu_notes/a100_mig.md
      - NVIDIA / CUDA: notes/gpu_notes/NVIDIA_CUDA/nvidia_cuda.md
  - Home: index.md
  - Internet Of Things:
      - AWS: notes/internet_of_things/AWS/storage.md
      - Azure:
          - Overview: notes/internet_of_things/Azure/overview.md
          - Azure Storage: notes/internet_of_things/Azure/Azure_Storage/azure_storage.md
      - General Notes: notes/internet_of_things/General Notes.md
      - TLS Security: notes/internet_of_things/TLS Security/TLS Security.md
  - Kubernetes:
      - Cheat Sheet: notes/kubernetes/basics.md
      - Greenfield: notes/kubernetes/greenfield_deployment.md
      - Sample Deployment (Django): notes/kubernetes/sample-django-deployment.md
      - Sample Deployment (Flask): notes/kubernetes/sample-flask-deployment.md
      - Azure Ingress\Cert\Static IP: notes/kubernetes/azure_ingress_cert_static_ip.md
  - Languages:
      - Bash:
          - Basics: notes/bash/basics.md
          - Sed: notes/bash/sed.md
          - SFTP: notes/bash/sftp/sftp.md
          - Zip and Unzip: notes/bash/zip_and_unzip.md
          - Screen: notes/bash/screen.md
          - TMUX: notes/bash/tmux/tmux.md
          - SSH: notes/bash/ssh.md
          - Environment Variables: notes/bash/environment_variables.md
          - VI: notes/bash/vi.md
          - Users: notes/bash/users.md
          - Processes: notes/bash/processes.md
          - Mount: notes/bash/mount.md
          - On Startup: notes/bash/startup.md
          - PDFs: notes/bash/pdfs.md
      - Python:
          - Installs: 
              - Base: notes/python/Installs.md
              - Environments: notes/python/Environments.md
          - Base Modules\Concepts:
              - Collection:
                  - Counter: notes/python/base_modules/collections/Counter.md
                  - default_dict(): notes/python/base_modules/collections/Default Dict.md
              - Pdb: notes/python/base_modules/Pdb.md
              - Strings: notes/python/base_modules/strings/Strings.md
              - map(): notes/python/base_modules/Map.md
              - input(): notes/python/base_modules/Input.md
              - Sets: notes/python/base_modules/Sets.md
              - P.B. Reference: notes/python/base_modules/Pass By Reference.md
              - args, kwargs: notes/python/base_modules/Args and Kwargs.md
              - zip(): notes/python/base_modules/Zip.md
              - Zip Files: notes/python/base_modules/zip_files.md
              - IO: notes/python/base_modules/io.md
              - servers: notes/python/base_modules/basic_servers.md
              - sorted(): notes/python/base_modules/Sorted.md
          - DICOM:
              - DICOM to img file: notes/python/dicom/dicom_to_viewable_img_file.md
          - Flask:
              - Basics: notes/python/flask/basics.md
              - Links to Check Out: notes/python/flask/links_to_checkout.md
          - Pandas: notes/python/pandas/basics.md
          - PIL: notes/python/PIL/basics.md
          - Seaborn: notes/python/seaborn/basics.md
          - Jupyter:
              - Run Remotely: notes/python/jupyter/basics.md
          - Advanced:
              - Decorators: notes/python/advanced/Decorators.md
              - Classes: notes/python/advanced/Classes.md
              - Generators: notes/python/advanced/Generators.md
          - RabbitMQ:
              - Hellow World: notes/python/rabbitmq/hello_world.md
          - S3: notes/python/s3.md
          - TinyDB: notes/python/tinydb/basics.md
      - SQL:
          - Postgres:
              - Postgres: notes/sql/postgres/Postgres.md
              - pgAdmin: notes/sql/postgres/pgadmin.md
          - SQL server: notes/sql/sql_server/Sql Server.md
          - sqlite:
              - Installing: notes/sql/sqlite/installing.md
              - Basics: notes/sql/sqlite/Basics.md
              - Useful Code: notes/sql/sqlite/useful_everyday_useage.md
          - mySQL: notes/sql/mysql/mySQL.md
      - HTML: notes/html/html_template.md
      - CSS: notes/css/css.md
      - SASS: notes/sass/sass.md
      - Javascript:
          - Basics: notes/javascript/basics.md
          - D3js:
              - d3js.org: notes/javascript/D3js/d3js.org/basics.md
              - D3.js - Rocha:
                  - Chapter 1: notes/javascript/D3js/Rocha/chapter_1/chapter-1.md
                  - Chapter 2: notes/javascript/D3js/Rocha/chapter_2/chapter-2.md
                  - Chapter 3: notes/javascript/D3js/Rocha/chapter_3/chapter-3.md
                  - Chapter 4: notes/javascript/D3js/Rocha/chapter_4/chapter-4.md
              - Links To Checkout: notes/javascript/D3js/links_to_checkout.md
          - NodeJS:
              - Issues Solved: notes/javascript/NodeJS/issues_solved.md
          - Vue:
              - Vue - Flask Integration: notes/javascript/Vue/single_page_app/basics.md
              - Links To Checkout: notes/javascript/Vue/links_to_checkout.md
      - Sample Web Layouts:
          - Holy Grail: notes/layouts/holy_grail.md
  - Martinos:
      - Cluster: notes/Martinos/cluster/cluster.md
  - MKDocs: notes/MKDocs/Quick Notes.md
  - Apache:
      - Basics: notes/apache/apache.md
  - Nginx:
      - Basics: notes/nginx/nginx.md
  - Singularity:
      - Install: notes/singularity/install.md
      - Basics: notes/singularity/basics.md
      - Use With Docker: notes/singularity/use_with_docker.md
      - Demo for QTIM: notes/singularity/demo_for_qtim.md
      - Demo for CU: notes/singularity/cu-singularity.md

extra_css:
  - css/extra.css
dev_addr: "0.0.0.0:8080"
theme:
  name: windmill-dark
  highlightjs: true
  hljs_style: obsidian
  include_search_page: true
  search_index_only: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   - javascripts/mathjax.js # If you want to provide your own file
